backend:
  name: git-gateway
  branch: main # یا master (هر شاخه‌ای که روی گیتهاب داری)

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "posts"
    label: "مقالات"
    folder: "posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "عنوان", name: "title", widget: "string"}
      - {label: "تاریخ انتشار", name: "date", widget: "datetime"}
      - {label: "تصویر شاخص", name: "image", widget: "image", required: false}
      - {label: "متن مقاله", name: "body", widget: "markdown"}
